CREATE DATABASE db_citas;

USE db_citas;

CREATE TABLE citas (
    id_cita BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_paciente BIGINT NOT NULL,
    id_doctor BIGINT NOT NULL,
    fecha_cita DATETIME NOT NULL,
    estado ENUM('PROGRAMADA', 'ATENDIDA', 'CANCELADA') NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

DELIMITER $$

CREATE TRIGGER trg_citas_before_insert
BEFORE INSERT ON citas
FOR EACH ROW
BEGIN
    SET NEW.estado = 'PROGRAMADA';
END$$

DELIMITER ;