spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=false

# Security
jwt.secret=${JWT_SECRET:mi_clave_secreta_muy_larga_para_seguridad_2026_auth_service}